<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="446451" started-at="2021-12-03T19:09:21 IST" finished-at="2021-12-03T19:16:47 IST">
    <groups>
    </groups>
    <test name="Test.4" duration-ms="72" started-at="2021-12-03T19:09:21 IST" finished-at="2021-12-03T19:09:21 IST">
    </test> <!-- Test.4 -->
    <test name="Test.5" duration-ms="292328" started-at="2021-12-03T19:09:21 IST" finished-at="2021-12-03T19:14:13 IST">
      <class name="Mavenfinal.TestFlighttcketbooking">
        <test-method status="PASS" signature="FlightTicketbook()[pri:0, instance:Mavenfinal.TestFlighttcketbooking@1356d4d4]" name="FlightTicketbook" duration-ms="230160" started-at="2021-12-03T19:09:21 IST" finished-at="2021-12-03T19:13:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FlightTicketbook -->
        <test-method status="PASS" signature="teardrops()[pri:0, instance:Mavenfinal.TestFlighttcketbooking@1356d4d4]" name="teardrops" is-config="true" duration-ms="62001" started-at="2021-12-03T19:13:11 IST" finished-at="2021-12-03T19:14:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardrops -->
      </class> <!-- Mavenfinal.TestFlighttcketbooking -->
    </test> <!-- Test.5 -->
    <test name="Test.3" duration-ms="296044" started-at="2021-12-03T19:09:21 IST" finished-at="2021-12-03T19:14:17 IST">
      <class name="Mavenfinal.TestRegistration">
        <test-method status="PASS" signature="Registration()[pri:0, instance:Mavenfinal.TestRegistration@28975c28]" name="Registration" duration-ms="288510" started-at="2021-12-03T19:09:21 IST" finished-at="2021-12-03T19:14:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Registration -->
        <test-method status="PASS" signature="teardrops()[pri:0, instance:Mavenfinal.TestRegistration@28975c28]" name="teardrops" is-config="true" duration-ms="7358" started-at="2021-12-03T19:14:09 IST" finished-at="2021-12-03T19:14:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardrops -->
      </class> <!-- Mavenfinal.TestRegistration -->
    </test> <!-- Test.3 -->
    <test name="Test.1" duration-ms="298201" started-at="2021-12-03T19:09:21 IST" finished-at="2021-12-03T19:14:19 IST">
      <class name="Mavenfinal.TestLogin">
        <test-method status="PASS" signature="Validatelogin()[pri:0, instance:Mavenfinal.TestLogin@683dbc2c]" name="Validatelogin" duration-ms="290032" started-at="2021-12-03T19:09:21 IST" finished-at="2021-12-03T19:14:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validatelogin -->
        <test-method status="PASS" signature="teardrops()[pri:0, instance:Mavenfinal.TestLogin@683dbc2c]" name="teardrops" is-config="true" duration-ms="8030" started-at="2021-12-03T19:14:11 IST" finished-at="2021-12-03T19:14:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardrops -->
      </class> <!-- Mavenfinal.TestLogin -->
    </test> <!-- Test.1 -->
    <test name="Test.2" duration-ms="446385" started-at="2021-12-03T19:09:21 IST" finished-at="2021-12-03T19:16:47 IST">
      <class name="Mavenfinal.TestPractisepage">
        <test-method status="PASS" signature="Practise1()[pri:0, instance:Mavenfinal.TestPractisepage@11c9af63]" name="Practise1" duration-ms="257179" started-at="2021-12-03T19:09:21 IST" finished-at="2021-12-03T19:13:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Practise1 -->
        <test-method status="FAIL" signature="Practise2()[pri:0, instance:Mavenfinal.TestPractisepage@11c9af63]" name="Practise2" duration-ms="188450" started-at="2021-12-03T19:13:38 IST" finished-at="2021-12-03T19:16:46 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
The link with textAppiumis broken with code403 expected [true] but found [false],
The link with textBroken Linkis broken with code404 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
The link with textAppiumis broken with code403 expected [true] but found [false],
The link with textBroken Linkis broken with code404 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Mavenfinal.TestPractisepage.Practise2(TestPractisepage.java:135)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Practise2 -->
        <test-method status="PASS" signature="teardrops()[pri:0, instance:Mavenfinal.TestPractisepage@11c9af63]" name="teardrops" is-config="true" duration-ms="522" started-at="2021-12-03T19:16:47 IST" finished-at="2021-12-03T19:16:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardrops -->
      </class> <!-- Mavenfinal.TestPractisepage -->
    </test> <!-- Test.2 -->
  </suite> <!-- Suite -->
</testng-results>
